# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               silvestro1
tagline:             my GitHub Page
description:         ...a place for experimentation and testing!
url:                 http://silvestro1.gihub.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Silvester Triebnig
  url:               https://silvestro1.github.io
  email:             silvestro1@gmx.at

# Custom vars
version:             1.0.0
